chore(types): usage of express.Request
express-validator/express-validator pull request #1007
Opened 2021-03-10 15:11 UTC by Divlo

## Description

Currently, when we have a `express` middleware that add properties to the `Request` object, we can access the properties in `meta.req` object in the `custom` of the `body` for example like this :
```ts
body('name') 
  .custom(async (name: string, meta) => {
    meta.req.user.name // access to the property
  })
```

To don't have errors in TypeScript, we do it like that :
```ts
import * as expressValidator from 'express-validator'

interface Request {
  [k: string]: any
  body?: any
  cookies?: Record<string, any>
  headers?: Record<string, any>
  params?: Record<string, any>
  query?: Record<string, any>
}

interface CustomRequest extends Request {
  user: { name: string }
}

declare module 'express-validator' {
  interface Meta {
    req: CustomRequest
    location: expressValidator.Location
    path: string
  }
}
```

It could be cool if we would not need to copy/paste the `Request` interface in our own code, so we could export it.

## To-do list

- [ ] I have added tests for what I changed.
Not relevant.

- [x] This pull request is ready to merge.

2021-03-10 15:46 UTC, fedeci reviewed
`express.Request` doesn't work?

2021-03-10 17:09 UTC, Divlo commented
It actually works, thanks for this fast reply!
Didn't know it worked, because the types are differents!

So now I have something like that :
```ts
import * as expressValidator from 'express-validator'
import { Request } from 'express'

interface CustomRequest extends Request {
  user: { name: string }
}

declare module 'express-validator' {
  interface Meta {
    req: CustomRequest
    location: expressValidator.Location
    path: string
  }
}
```

It could be cool, if I would not need to do it for `express-validator` side, since I already do it for `express` :
```ts
declare global {
  namespace Express {
    interface Request {
      user: { name: string }
    }
  }
}
```

Is there is any way that `express-validator` take the `express.Request` interface ?

2021-03-10 19:22 UTC, fedeci commented
Related to #911

2021-03-10 19:41 UTC, fedeci requested changes

2021-03-10 19:41 UTC, fedeci commented on src/base.ts
> -export interface Request {
`express-validator.Request` is a more generic type than `express.Request`. Furthermore in the internal API we don't require all those methods and types defined in `express.Request` that are causing problems with the CI.

2021-03-11 17:30 UTC, Divlo commented on src/chain/sanitizers-impl.spec.ts
> +    const meta: Meta = { req: {} as Request, location: 'body', path: 'foo' };
Right, thanks for your review!
I'll wait for @gustavohenke opinion about this type change, until further commits.

2021-03-25 12:47 UTC, Divlo commented
Thanks for your help and your time, I guess it's fine like that!
I'm closing this PR since it would probably be the wrong TypeScript types to use `express.Request`.

2021-03-25 12:47 UTC, closed without merging