fix: use `Symbol` instead of `string` as context key
express-validator/express-validator pull request #1014
Opened 2021-03-30 20:45 UTC by fedeci

## Description

We change the context key from  a `string` type, which does not guarantee unicity, to a [`Symbol`](https://developer.mozilla.org/it/docs/Web/JavaScript/Reference/Global_Objects/Symbol).

## To-do list

- [x] I have added tests for what I changed.

- [x] This pull request is ready to merge.

2021-03-31 22:15 UTC, gustavohenke requested changes
Hah, it used to be like this in the past 😂 
#813 303b5eb927f9f173412b5e45097f5edd9810ecb1 https://github.com/express-validator/express-validator/releases/tag/v6.3.1

I guess we should add some comments to that line...

2021-04-02 08:34 UTC, fedeci commented on src/base.ts
> +export const contextsKey = Symbol('contexts');
```suggestion
// Not using simbols because of #813
export const contextsKey = 'express-validator#contexts';
```

2021-04-02 08:38 UTC, fedeci commented on src/base.ts
> +// Not using simbols because of #813
```suggestion
// Not using Symbol because of #813
```
Oops Italian grammar🤦🏻‍♂️

2021-04-05 06:31 UTC, gustavohenke approved these changes

2021-04-05 07:22 UTC, merged