chore(dep): bump validator to 3.16.0
express-validator/express-validator pull request #1025
Opened 2021-04-27 16:14 UTC by rsdmike

## Description
Updated validator to version 3.16.0 to address issue #1021. First time contributor here -- I've ensured the tests pass by added the new function for `isLicensePlate` by following how other functions are added. If I missed anything let me know.

## To-do list

- [ ] I have added tests for what I changed.

- [ ] This pull request is ready to merge.

2021-04-27 19:52 UTC, fedeci requested changes
Thanks @rsdmike for the PR!
`13.6.1` was a tagged version of `validator` that was never published on the npm registry because it was joined with `13.6.0`😄.
Apart from `isLicensePlate` we should also add the new locales and the new options of v13.6.0, can you tackle those too?

2021-04-27 19:52 UTC, fedeci commented on src/chain/validators-impl.ts
> +  }
```suggestion
  isLicensePlate(locale: Options.LicensePlateLocale) {
    return this.addStandardValidation(validator.isLicensePlate, locale);
  }
```

2021-04-27 19:52 UTC, fedeci commented on declarations/validator.d.ts
> +    options: import('../src/options').LicensePlateLocale,
```suggestion
    locale: import('../src/options').LicensePlateLocale,
```

2021-04-28 16:33 UTC, rsdmike commented
@fedeci I'll take a look

2021-05-24 18:35 UTC, fedeci commented
Hi there, any update on this?

2021-07-27 20:32 UTC, fedeci commented
Closing as stale

2021-07-27 20:32 UTC, closed without merging

2021-08-15 03:25 UTC, rsdmike commented
Hey @fedeci, I'm sorry I didn't get around to this.

2021-08-15 07:25 UTC, fedeci commented
Don't worry, OSS is great also for this! Your credits are still in the commits of the other PR!