Add hide() method
express-validator/express-validator pull request #1305
Opened 2024-07-17 05:45 UTC by skysign

## Description

I'd like to contribute this commit.
This is an implementation for #1304.

## To-do list

- [ ] I have added tests for what I changed.

- [X] This pull request is ready to merge.

2024-07-24 14:14 UTC, gustavohenke reviewed
General question about this PR before I make some nitpicks:
What do you think if the default behaviour was to simply omit the value in the errors, but if a hidden value is set, use it?

In other words, `query('api_key').hide()` would get reported as

```js
{ msg: 'Invalid value', path: 'api_key', location: 'query' }
```

whereas `query('api_key').hide('******')` would get reported as

```js
{ msg: 'Invalid value', path: 'api_key', location: 'query', value: '******' }
```

2024-07-25 00:47 UTC, skysign commented
> General question about this PR before I make some nitpicks: What do you think if the default behaviour was to simply omit the value in the errors, but if a hidden value is set, use it?
> 
> In other words, `query('api_key').hide()` would get reported as
> 
> ```js
> { msg: 'Invalid value', path: 'api_key', location: 'query' }
> ```
> 
> whereas `query('api_key').hide('******')` would get reported as
> 
> ```js
> { msg: 'Invalid value', path: 'api_key', location: 'query', value: '******' }
> ```

I think that it is a good idea, let me update my PR. :)

2024-07-25 08:01 UTC, skysign commented
As per your suggestion, the behavior of hide() method is updated.
Please review this PR. :)

2024-07-29 02:17 UTC, skysign commented
coverage is increased by adding new test case.
Please review this PR. :)

2024-08-03 11:34 UTC, gustavohenke requested changes
Hey! I tried to make up for my delay in reviewing your PR, as you can see there are a few large changes 😅 

I think the docs need to have some of the suggestions applied, but use your judgement.

I also don't know yet what the behaviour should be for `oneOf()`, but it might be fine to ship this without support for `oneOf` for now.
WDYT?

2024-08-03 11:34 UTC, gustavohenke commented on src/chain/context-handler.ts
> +   * Hide field's value in the returning errors of validationResult() method.
```suggestion
   * Hide the field's value in errors returned by `validationResult()`.
```

2024-08-03 11:34 UTC, gustavohenke commented on src/chain/context-handler.ts
> +   * The value might be confidential information (such as api key), so we replace its value.
```suggestion
   * If the value is confidential information (such as api key),
   * you might want to call this method to prevent exposing it.
```

2024-08-03 11:34 UTC, gustavohenke commented on src/chain/context-handler.ts
> +   * - if it's not given, by default, '********'.
```suggestion
   * @param hiddenValue? String to replace the field's value with.
   *   If it's not set, the field value is removed from errors.
```

2024-08-03 11:34 UTC, gustavohenke commented on docs/api/validation-chain.md
> +:::info
I'm not sure about the examples in this block.
Maybe we can get away with something like this?

```ts
// Omits the value in the errors
query('api_key').custom(isValidKey).hide(); 

// Replaces the value in the errors with '*****'
query('api_key').custom(isValidKey).hide('*****'); 
```

2024-08-05 11:34 UTC, skysign commented
> Hey! I tried to make up for my delay in reviewing your PR, as you can see there are a few large changes 😅
> 
> I think the docs need to have some of the suggestions applied, but use your judgement.
> 
> I also don't know yet what the behaviour should be for `oneOf()`, but it might be fine to ship this without support for `oneOf` for now. WDYT?

Thanks for your suggestion regarding docs. Now, they are resolved.
I prefer that we may ship without support for `oneOf`.
How about to discuss in another PR regarding `oneOf`?

2024-08-09 05:03 UTC, skysign reviewed
LGTM :)

2024-08-11 00:50 UTC, gustavohenke approved these changes

2024-08-11 01:15 UTC, merged

2024-08-11 10:39 UTC, gustavohenke commented
This PR has been released - check out https://github.com/express-validator/express-validator/releases/tag/v7.2.0 😃